[15/Aug/2018 09:43:52] ERROR [django.request:284] Internal Server Error: /admin/item-details/akjghjghjkjgk-16/
Traceback (most recent call last):
  File "/Users/apple/workspace/afxal/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/apple/workspace/afxal/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/apple/workspace/afxal/sun_groups/app/home/views.py", line 23, in item_details
    context['dish'] = DishSerializer(dish, many=False).data
  File "/Users/apple/workspace/afxal/env/lib/python2.7/site-packages/rest_framework/serializers.py", line 531, in data
    ret = super(Serializer, self).data
  File "/Users/apple/workspace/afxal/env/lib/python2.7/site-packages/rest_framework/serializers.py", line 262, in data
    self._data = self.to_representation(self.instance)
  File "/Users/apple/workspace/afxal/env/lib/python2.7/site-packages/rest_framework/serializers.py", line 483, in to_representation
    fields = self._readable_fields
  File "/Users/apple/workspace/afxal/env/lib/python2.7/site-packages/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/apple/workspace/afxal/env/lib/python2.7/site-packages/rest_framework/serializers.py", line 377, in _readable_fields
    field for field in self.fields.values()
  File "/Users/apple/workspace/afxal/env/lib/python2.7/site-packages/rest_framework/serializers.py", line 363, in fields
    for key, value in self.get_fields().items():
  File "/Users/apple/workspace/afxal/env/lib/python2.7/site-packages/rest_framework/serializers.py", line 984, in get_fields
    field_names = self.get_field_names(declared_fields, info)
  File "/Users/apple/workspace/afxal/env/lib/python2.7/site-packages/rest_framework/serializers.py", line 1081, in get_field_names
    serializer_class=self.__class__.__name__
AssertionError: The field 'category_name' was declared on serializer DishSerializer, but has not been included in the 'fields' option.
[15/Aug/2018 09:45:56] WARNING [django.request:182] Not Found: /admin/item-details/afsal-19
